# Generated by Django 4.0.6 on 2022-08-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drftest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordination',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='drftest.client'),
        ),
    ]
